[window]
decorations = "None"

[font]
size = 14.0

[font.normal]
family = "CommitMono Nerd Font"
style = "Regular"

[font.bold]
family = "CommitMono Nerd Font"
style = "Bold"

[font.italic]
family = "CommitMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CommitMono Nerd Font"
style = "Bold Italic"

[general]
import = ["~/.config/alacritty/carbonfox.toml"]
