format = """\
$username\
[@](fg:#dfdfe0 bg:#282828)\
$hostname\
$directory\
$git_branch\
$git_status\
$git_metrics\
$character
"""
right_format = """
$cmd_duration\
[ at](bg:#be95ff fg:#161616)
$time
"""

[character]
success_symbol = '[▊](fg:#25be6a bg:#161616)'
error_symbol = '[▊](fg:#ee5396 bg:#161616)'
vimcmd_symbol = '[▊](fg:#08bdba bg:#161616)'

[username]
show_always = true
format = '[ $user](fg:#dfdfe0 bg:#282828)'

[hostname]
ssh_only = false
format = '[$hostname ](fg:#dfdfe0 bg:#282828)'

[directory]
format = "[ $path ]($style)"
style = "fg:#161616 bg:#dfdfe0 bold"

[git_branch]
format = '[ $branch(:$remote_branch)]($style)'
style = "fg:#08bdba bg:#282828"

[git_status]
format = '$ahead_behind[$stashed]($style)[$deleted](fg:#ee5396 bg:#282828)[$renamed](fg:#be95ff bg:#282828)[$modified](fg:#FFF050 bg:#282828)[$typechanged](fg:#be95ff bg:#282828)[$staged](fg:#25be6a bg:#282828)[$untracked](fg:#7B7C7E bg:#282828)'
style = "fg:#dfdfe0 bg:#282828"
conflicted = "conflicted"
ahead = "[, ahead by ${count} ](fg:#08bdba bg:#282828)"
behind = "[, behind by ${count} ](fg:#08bdba bg:#282828)"
diverged = "[ ${ahead_count} ahead, ${behind_count} behind ]"
up_to_date = "[ ](bg:#282828)"
untracked = "?${count} "
stashed = "stashed ${count} "
modified = "!${count} "
staged = "+${count} "
renamed = ">${count} "
deleted = "x${count} "
typechanged = "@${count}"
ignore_submodules = true

[git_metrics]
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
added_style = "fg:#25be6a bg:#282828"
deleted_style = "fg:#ee5396 bg:#282828"
disabled = false

[time]
disabled = false
time_format = "%I:%M:%S %p" # Hour:Minute Format
format = '[ $time ](bg:#be95ff fg:#161616)'

[cmd_duration]
disabled = false
min_time = 0
format = '[ $duration](bg:#be95ff fg:#161616)'

