format = """\
$username\
$hostname\
$python\
$directory\
$sudo\
$character
"""
right_format = """
$cmd_duration\
$time
"""

[character]
success_symbol = '[█](fg:#25be6a)'
error_symbol = '[█](fg:#ee5396)'
vimcmd_symbol = '[█](fg:#08bdba)'

[username]
show_always = false
format = '[ $user](bg:#282828 fg:#dfdfe0)'

[hostname]
ssh_only = true
format = '[@$hostname ](bg:#282828 fg:#dfdfe0)'

[directory]
format = "[ $path ]($style)"
style = "fg:#dfdfe0 bg:#282828 bold"

[git_branch]
enabled = false
format = '[→ $branch(:$remote_branch ) ]($style)'
style = "fg:#08bdba bg:#282828"

[git_commit]
enabled = false
commit_hash_length = 7
format = '[\($hash$tag\) ]($style)'
style = "fg:#08bdba bg:#282828"

[git_status]
enabled = false
format = "$ahead_behind[$stashed](fg:#dfdfe0 bg:#282828)[$deleted](fg:#ee5396 bg:#282828)[$renamed](fg:#be95ff bg:#282828)[$modified](fg:#FFF050 bg:#282828)[$typechanged](fg:#be95ff bg:#282828)[$staged](fg:#25be6a bg:#282828)[$untracked](fg:#b6b8bb bg:#282828)"
conflicted = "conflicted" 
ahead = "[, ahead by ${count} ](fg:#08bdba bg:#282828)"
behind = "[, behind by ${count} ](fg:#08bdba bg:#282828)"
diverged = "[${ahead_count} ahead, ${behind_count} behind ]"
up_to_date = "[](bg:#282828)"
untracked = "?${count} "
stashed = "stashed ${count} "
modified = "!${count} "
staged = "s${count} "
renamed = "r${count}, "
deleted = "d${count}, "
typechanged = ".${count}"
ignore_submodules = true

[git_metrics]
enabled = false
format = '([+$added ]($added_style))([-$deleted ]($deleted_style))'
added_style = "fg:#25be6a bg:#282828"
deleted_style = "fg:#ee5396 bg:#282828"
disabled = false

[time]
disabled = false
time_format = "%I:%M:%S %p" # Hour:Minute Format
format = '[ $time ](fg:#dfdfe0 bg:#282828)'


[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
format = '[ $duration ](fg:#282828 bg:#b6b8bb)'

[python]
format = '[(\($virtualenv\))](bg:#282828 fg:#dfdfe0 italic)'
